/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/projetos': typeof ProjetosIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/projetos/$slug'
    | '/servicos/$slug'
    | '/projetos/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/projetos/$slug'
    | '/servicos/$slug'
    | '/projetos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/obrigado'
    | '/orcamento'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/projetos/$slug'
    | '/servicos/$slug'
    | '/projetos/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ObrigadoRoute: ObrigadoRoute,
  OrcamentoRoute: OrcamentoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
